import { FcGoogle } from "react-icons/fc";
import { AiTwotoneMail } from "react-icons/ai";
import { MdQrCodeScanner } from "react-icons/md";

// Available Sign-In Methods for dynamic rendering
export const SIGN_IN_METHODS = [
  { id: "google", label: "Sign in with Google", icon: FcGoogle },
  { id: "email", label: "Sign in with Email", icon: AiTwotoneMail },
];

export const LOGIN_TYPES = {
  PHONE: "phone",
  EMAIL: "email",
};

// Comprehensive list of country codes with flag emojis
export const COUNTRY_CODES = [
  {"code": "+93", "country": "Afghanistan", "flag": "\ud83c\udde6\ud83c\uddeb", "iso": "AF"},
  {"code": "+355", "country": "Albania", "flag": "\ud83c\udde6\ud83c\uddf1", "iso": "AL"},
  {"code": "+213", "country": "Algeria", "flag": "\ud83c\udde9\ud83c\uddff", "iso": "DZ"},
  {"code": "+1684", "country": "American Samoa", "flag": "\ud83c\udde6\ud83c\uddf8", "iso": "AS"},
  {"code": "+376", "country": "Andorra", "flag": "\ud83c\udde6\ud83c\udde9", "iso": "AD"},
  {"code": "+244", "country": "Angola", "flag": "\ud83c\udde6\ud83c\uddf4", "iso": "AO"},
  {"code": "+1264", "country": "Anguilla", "flag": "\ud83c\udde6\ud83c\uddee", "iso": "AI"},
  {"code": "+1268", "country": "Antigua and Barbuda", "flag": "\ud83c\udde6\ud83c\uddec", "iso": "AG"},
  {"code": "+54", "country": "Argentina", "flag": "\ud83c\udde6\ud83c\uddf7", "iso": "AR"},
  {"code": "+374", "country": "Armenia", "flag": "\ud83c\udde6\ud83c\uddf2", "iso": "AM"},
  {"code": "+297", "country": "Aruba", "flag": "\ud83c\udde6\ud83c\uddfc", "iso": "AW"},
  {"code": "+61", "country": "Australia", "flag": "\ud83c\udde6\ud83c\uddfa", "iso": "AU"},
  {"code": "+43", "country": "Austria", "flag": "\ud83c\udde6\ud83c\uddf9", "iso": "AT"},
  {"code": "+994", "country": "Azerbaijan", "flag": "\ud83c\udde6\ud83c\uddff", "iso": "AZ"},
  {"code": "+1242", "country": "Bahamas", "flag": "\ud83c\udde7\ud83c\uddf8", "iso": "BS"},
  {"code": "+973", "country": "Bahrain", "flag": "\ud83c\udde7\ud83c\udded", "iso": "BH"},
  {"code": "+880", "country": "Bangladesh", "flag": "\ud83c\udde7\ud83c\udde9", "iso": "BD"},
  {"code": "+1246", "country": "Barbados", "flag": "\ud83c\udde7\ud83c\udde7", "iso": "BB"},
  {"code": "+375", "country": "Belarus", "flag": "\ud83c\udde7\ud83c\uddfe", "iso": "BY"},
  {"code": "+32", "country": "Belgium", "flag": "\ud83c\udde7\ud83c\uddea", "iso": "BE"},
  {"code": "+501", "country": "Belize", "flag": "\ud83c\udde7\ud83c\uddff", "iso": "BZ"},
  {"code": "+229", "country": "Benin", "flag": "\ud83c\udde7\ud83c\uddef", "iso": "BJ"},
  {"code": "+1441", "country": "Bermuda", "flag": "\ud83c\udde7\ud83c\uddf2", "iso": "BM"},
  {"code": "+975", "country": "Bhutan", "flag": "\ud83c\udde7\ud83c\uddf9", "iso": "BT"},
  {"code": "+591", "country": "Bolivia", "flag": "\ud83c\udde7\ud83c\uddf4", "iso": "BO"},
  {"code": "+387", "country": "Bosnia and Herzegovina", "flag": "\ud83c\udde7\ud83c\udde6", "iso": "BA"},
  {"code": "+267", "country": "Botswana", "flag": "\ud83c\udde7\ud83c\uddfc", "iso": "BW"},
  {"code": "+47", "country": "Bouvet Island", "flag": "\ud83c\udde7\ud83c\uddfb", "iso": "BV"},
  {"code": "+55", "country": "Brazil", "flag": "\ud83c\udde7\ud83c\uddf7", "iso": "BR"},
  {"code": "+246", "country": "British Indian Ocean Territory", "flag": "\ud83c\uddee\ud83c\uddf4", "iso": "IO"},
  {"code": "+1284", "country": "British Virgin Islands", "flag": "\ud83c\uddfb\ud83c\uddec", "iso": "VG"},
  {"code": "+673", "country": "Brunei", "flag": "\ud83c\udde7\ud83c\uddf3", "iso": "BN"},
  {"code": "+359", "country": "Bulgaria", "flag": "\ud83c\udde7\ud83c\uddec", "iso": "BG"},
  {"code": "+226", "country": "Burkina Faso", "flag": "\ud83c\udde7\ud83c\uddeb", "iso": "BF"},
  {"code": "+257", "country": "Burundi", "flag": "\ud83c\udde7\ud83c\uddee", "iso": "BI"},
  {"code": "+855", "country": "Cambodia", "flag": "\ud83c\uddf0\ud83c\udded", "iso": "KH"},
  {"code": "+237", "country": "Cameroon", "flag": "\ud83c\udde8\ud83c\uddf2", "iso": "CM"},
  {"code": "+1204", "country": "Canada", "flag": "\ud83c\udde8\ud83c\udde6", "iso": "CA"},
  {"code": "+238", "country": "Cape Verde", "flag": "\ud83c\udde8\ud83c\uddfb", "iso": "CV"},
  {"code": "+599", "country": "Caribbean Netherlands", "flag": "\ud83c\udde7\ud83c\uddf6", "iso": "BQ"},
  {"code": "+1345", "country": "Cayman Islands", "flag": "\ud83c\uddf0\ud83c\uddfe", "iso": "KY"},
  {"code": "+236", "country": "Central African Republic", "flag": "\ud83c\udde8\ud83c\uddeb", "iso": "CF"},
  {"code": "+235", "country": "Chad", "flag": "\ud83c\uddf9\ud83c\udde9", "iso": "TD"},
  {"code": "+56", "country": "Chile", "flag": "\ud83c\udde8\ud83c\uddf1", "iso": "CL"},
  {"code": "+86", "country": "China", "flag": "\ud83c\udde8\ud83c\uddf3", "iso": "CN"},
  {"code": "+61", "country": "Christmas Island", "flag": "\ud83c\udde8\ud83c\uddfd", "iso": "CX"},
  {"code": "+61", "country": "Cocos (Keeling) Islands", "flag": "\ud83c\udde8\ud83c\udde8", "iso": "CC"},
  {"code": "+57", "country": "Colombia", "flag": "\ud83c\udde8\ud83c\uddf4", "iso": "CO"},
  {"code": "+269", "country": "Comoros", "flag": "\ud83c\uddf0\ud83c\uddf2", "iso": "KM"},
  {"code": "+242", "country": "Congo", "flag": "\ud83c\udde8\ud83c\uddec", "iso": "CG"},
  {"code": "+682", "country": "Cook Islands", "flag": "\ud83c\udde8\ud83c\uddf0", "iso": "CK"},
  {"code": "+506", "country": "Costa Rica", "flag": "\ud83c\udde8\ud83c\uddf7", "iso": "CR"},
  {"code": "+385", "country": "Croatia", "flag": "\ud83c\udded\ud83c\uddf7", "iso": "HR"},
  {"code": "+53", "country": "Cuba", "flag": "\ud83c\udde8\ud83c\uddfa", "iso": "CU"},
  {"code": "+599", "country": "Cura\u00e7ao", "flag": "\ud83c\udde8\ud83c\uddfc", "iso": "CW"},
  {"code": "+357", "country": "Cyprus", "flag": "\ud83c\udde8\ud83c\uddfe", "iso": "CY"},
  {"code": "+420", "country": "Czechia", "flag": "\ud83c\udde8\ud83c\uddff", "iso": "CZ"},
  {"code": "+243", "country": "DR Congo", "flag": "\ud83c\udde8\ud83c\udde9", "iso": "CD"},
  {"code": "+45", "country": "Denmark", "flag": "\ud83c\udde9\ud83c\uddf0", "iso": "DK"},
  {"code": "+253", "country": "Djibouti", "flag": "\ud83c\udde9\ud83c\uddef", "iso": "DJ"},
  {"code": "+1767", "country": "Dominica", "flag": "\ud83c\udde9\ud83c\uddf2", "iso": "DM"},
  {"code": "+1809", "country": "Dominican Republic", "flag": "\ud83c\udde9\ud83c\uddf4", "iso": "DO"},
  {"code": "+593", "country": "Ecuador", "flag": "\ud83c\uddea\ud83c\udde8", "iso": "EC"},
  {"code": "+20", "country": "Egypt", "flag": "\ud83c\uddea\ud83c\uddec", "iso": "EG"},
  {"code": "+503", "country": "El Salvador", "flag": "\ud83c\uddf8\ud83c\uddfb", "iso": "SV"},
  {"code": "+240", "country": "Equatorial Guinea", "flag": "\ud83c\uddec\ud83c\uddf6", "iso": "GQ"},
  {"code": "+291", "country": "Eritrea", "flag": "\ud83c\uddea\ud83c\uddf7", "iso": "ER"},
  {"code": "+372", "country": "Estonia", "flag": "\ud83c\uddea\ud83c\uddea", "iso": "EE"},
  {"code": "+268", "country": "Eswatini", "flag": "\ud83c\uddf8\ud83c\uddff", "iso": "SZ"},
  {"code": "+251", "country": "Ethiopia", "flag": "\ud83c\uddea\ud83c\uddf9", "iso": "ET"},
  {"code": "+500", "country": "Falkland Islands", "flag": "\ud83c\uddeb\ud83c\uddf0", "iso": "FK"},
  {"code": "+298", "country": "Faroe Islands", "flag": "\ud83c\uddeb\ud83c\uddf4", "iso": "FO"},
  {"code": "+679", "country": "Fiji", "flag": "\ud83c\uddeb\ud83c\uddef", "iso": "FJ"},
  {"code": "+358", "country": "Finland", "flag": "\ud83c\uddeb\ud83c\uddee", "iso": "FI"},
  {"code": "+33", "country": "France", "flag": "\ud83c\uddeb\ud83c\uddf7", "iso": "FR"},
  {"code": "+594", "country": "French Guiana", "flag": "\ud83c\uddec\ud83c\uddeb", "iso": "GF"},
  {"code": "+689", "country": "French Polynesia", "flag": "\ud83c\uddf5\ud83c\uddeb", "iso": "PF"},
  {"code": "+262", "country": "French Southern and Antarctic Lands", "flag": "\ud83c\uddf9\ud83c\uddeb", "iso": "TF"},
  {"code": "+241", "country": "Gabon", "flag": "\ud83c\uddec\ud83c\udde6", "iso": "GA"},
  {"code": "+220", "country": "Gambia", "flag": "\ud83c\uddec\ud83c\uddf2", "iso": "GM"},
  {"code": "+995", "country": "Georgia", "flag": "\ud83c\uddec\ud83c\uddea", "iso": "GE"},
  {"code": "+49", "country": "Germany", "flag": "\ud83c\udde9\ud83c\uddea", "iso": "DE"},
  {"code": "+233", "country": "Ghana", "flag": "\ud83c\uddec\ud83c\udded", "iso": "GH"},
  {"code": "+350", "country": "Gibraltar", "flag": "\ud83c\uddec\ud83c\uddee", "iso": "GI"},
  {"code": "+30", "country": "Greece", "flag": "\ud83c\uddec\ud83c\uddf7", "iso": "GR"},
  {"code": "+299", "country": "Greenland", "flag": "\ud83c\uddec\ud83c\uddf1", "iso": "GL"},
  {"code": "+1473", "country": "Grenada", "flag": "\ud83c\uddec\ud83c\udde9", "iso": "GD"},
  {"code": "+590", "country": "Guadeloupe", "flag": "\ud83c\uddec\ud83c\uddf5", "iso": "GP"},
  {"code": "+1671", "country": "Guam", "flag": "\ud83c\uddec\ud83c\uddfa", "iso": "GU"},
  {"code": "+502", "country": "Guatemala", "flag": "\ud83c\uddec\ud83c\uddf9", "iso": "GT"},
  {"code": "+44", "country": "Guernsey", "flag": "\ud83c\uddec\ud83c\uddec", "iso": "GG"},
  {"code": "+224", "country": "Guinea", "flag": "\ud83c\uddec\ud83c\uddf3", "iso": "GN"},
  {"code": "+245", "country": "Guinea-Bissau", "flag": "\ud83c\uddec\ud83c\uddfc", "iso": "GW"},
  {"code": "+592", "country": "Guyana", "flag": "\ud83c\uddec\ud83c\uddfe", "iso": "GY"},
  {"code": "+509", "country": "Haiti", "flag": "\ud83c\udded\ud83c\uddf9", "iso": "HT"},
  {"code": "+504", "country": "Honduras", "flag": "\ud83c\udded\ud83c\uddf3", "iso": "HN"},
  {"code": "+852", "country": "Hong Kong", "flag": "\ud83c\udded\ud83c\uddf0", "iso": "HK"},
  {"code": "+36", "country": "Hungary", "flag": "\ud83c\udded\ud83c\uddfa", "iso": "HU"},
  {"code": "+354", "country": "Iceland", "flag": "\ud83c\uddee\ud83c\uddf8", "iso": "IS"},
  {"code": "+91", "country": "India", "flag": "\ud83c\uddee\ud83c\uddf3", "iso": "IN"},
  {"code": "+62", "country": "Indonesia", "flag": "\ud83c\uddee\ud83c\udde9", "iso": "ID"},
  {"code": "+98", "country": "Iran", "flag": "\ud83c\uddee\ud83c\uddf7", "iso": "IR"},
  {"code": "+964", "country": "Iraq", "flag": "\ud83c\uddee\ud83c\uddf6", "iso": "IQ"},
  {"code": "+353", "country": "Ireland", "flag": "\ud83c\uddee\ud83c\uddea", "iso": "IE"},
  {"code": "+44", "country": "Isle of Man", "flag": "\ud83c\uddee\ud83c\uddf2", "iso": "IM"},
  {"code": "+972", "country": "Israel", "flag": "\ud83c\uddee\ud83c\uddf1", "iso": "IL"},
  {"code": "+39", "country": "Italy", "flag": "\ud83c\uddee\ud83c\uddf9", "iso": "IT"},
  {"code": "+225", "country": "Ivory Coast", "flag": "\ud83c\udde8\ud83c\uddee", "iso": "CI"},
  {"code": "+1876", "country": "Jamaica", "flag": "\ud83c\uddef\ud83c\uddf2", "iso": "JM"},
  {"code": "+81", "country": "Japan", "flag": "\ud83c\uddef\ud83c\uddf5", "iso": "JP"},
  {"code": "+44", "country": "Jersey", "flag": "\ud83c\uddef\ud83c\uddea", "iso": "JE"},
  {"code": "+962", "country": "Jordan", "flag": "\ud83c\uddef\ud83c\uddf4", "iso": "JO"},
  {"code": "+76", "country": "Kazakhstan", "flag": "\ud83c\uddf0\ud83c\uddff", "iso": "KZ"},
  {"code": "+254", "country": "Kenya", "flag": "\ud83c\uddf0\ud83c\uddea", "iso": "KE"},
  {"code": "+686", "country": "Kiribati", "flag": "\ud83c\uddf0\ud83c\uddee", "iso": "KI"},
  {"code": "+383", "country": "Kosovo", "flag": "\ud83c\uddfd\ud83c\uddf0", "iso": "XK"},
  {"code": "+965", "country": "Kuwait", "flag": "\ud83c\uddf0\ud83c\uddfc", "iso": "KW"},
  {"code": "+996", "country": "Kyrgyzstan", "flag": "\ud83c\uddf0\ud83c\uddec", "iso": "KG"},
  {"code": "+856", "country": "Laos", "flag": "\ud83c\uddf1\ud83c\udde6", "iso": "LA"},
  {"code": "+371", "country": "Latvia", "flag": "\ud83c\uddf1\ud83c\uddfb", "iso": "LV"},
  {"code": "+961", "country": "Lebanon", "flag": "\ud83c\uddf1\ud83c\udde7", "iso": "LB"},
  {"code": "+266", "country": "Lesotho", "flag": "\ud83c\uddf1\ud83c\uddf8", "iso": "LS"},
  {"code": "+231", "country": "Liberia", "flag": "\ud83c\uddf1\ud83c\uddf7", "iso": "LR"},
  {"code": "+218", "country": "Libya", "flag": "\ud83c\uddf1\ud83c\uddfe", "iso": "LY"},
  {"code": "+423", "country": "Liechtenstein", "flag": "\ud83c\uddf1\ud83c\uddee", "iso": "LI"},
  {"code": "+370", "country": "Lithuania", "flag": "\ud83c\uddf1\ud83c\uddf9", "iso": "LT"},
  {"code": "+352", "country": "Luxembourg", "flag": "\ud83c\uddf1\ud83c\uddfa", "iso": "LU"},
  {"code": "+853", "country": "Macau", "flag": "\ud83c\uddf2\ud83c\uddf4", "iso": "MO"},
  {"code": "+261", "country": "Madagascar", "flag": "\ud83c\uddf2\ud83c\uddec", "iso": "MG"},
  {"code": "+265", "country": "Malawi", "flag": "\ud83c\uddf2\ud83c\uddfc", "iso": "MW"},
  {"code": "+60", "country": "Malaysia", "flag": "\ud83c\uddf2\ud83c\uddfe", "iso": "MY"},
  {"code": "+960", "country": "Maldives", "flag": "\ud83c\uddf2\ud83c\uddfb", "iso": "MV"},
  {"code": "+223", "country": "Mali", "flag": "\ud83c\uddf2\ud83c\uddf1", "iso": "ML"},
  {"code": "+356", "country": "Malta", "flag": "\ud83c\uddf2\ud83c\uddf9", "iso": "MT"},
  {"code": "+692", "country": "Marshall Islands", "flag": "\ud83c\uddf2\ud83c\udded", "iso": "MH"},
  {"code": "+596", "country": "Martinique", "flag": "\ud83c\uddf2\ud83c\uddf6", "iso": "MQ"},
  {"code": "+222", "country": "Mauritania", "flag": "\ud83c\uddf2\ud83c\uddf7", "iso": "MR"},
  {"code": "+230", "country": "Mauritius", "flag": "\ud83c\uddf2\ud83c\uddfa", "iso": "MU"},
  {"code": "+262", "country": "Mayotte", "flag": "\ud83c\uddfe\ud83c\uddf9", "iso": "YT"},
  {"code": "+52", "country": "Mexico", "flag": "\ud83c\uddf2\ud83c\uddfd", "iso": "MX"},
  {"code": "+691", "country": "Micronesia", "flag": "\ud83c\uddeb\ud83c\uddf2", "iso": "FM"},
  {"code": "+373", "country": "Moldova", "flag": "\ud83c\uddf2\ud83c\udde9", "iso": "MD"},
  {"code": "+377", "country": "Monaco", "flag": "\ud83c\uddf2\ud83c\udde8", "iso": "MC"},
  {"code": "+976", "country": "Mongolia", "flag": "\ud83c\uddf2\ud83c\uddf3", "iso": "MN"},
  {"code": "+382", "country": "Montenegro", "flag": "\ud83c\uddf2\ud83c\uddea", "iso": "ME"},
  {"code": "+1664", "country": "Montserrat", "flag": "\ud83c\uddf2\ud83c\uddf8", "iso": "MS"},
  {"code": "+212", "country": "Morocco", "flag": "\ud83c\uddf2\ud83c\udde6", "iso": "MA"},
  {"code": "+258", "country": "Mozambique", "flag": "\ud83c\uddf2\ud83c\uddff", "iso": "MZ"},
  {"code": "+95", "country": "Myanmar", "flag": "\ud83c\uddf2\ud83c\uddf2", "iso": "MM"},
  {"code": "+264", "country": "Namibia", "flag": "\ud83c\uddf3\ud83c\udde6", "iso": "NA"},
  {"code": "+674", "country": "Nauru", "flag": "\ud83c\uddf3\ud83c\uddf7", "iso": "NR"},
  {"code": "+977", "country": "Nepal", "flag": "\ud83c\uddf3\ud83c\uddf5", "iso": "NP"},
  {"code": "+31", "country": "Netherlands", "flag": "\ud83c\uddf3\ud83c\uddf1", "iso": "NL"},
  {"code": "+687", "country": "New Caledonia", "flag": "\ud83c\uddf3\ud83c\udde8", "iso": "NC"},
  {"code": "+64", "country": "New Zealand", "flag": "\ud83c\uddf3\ud83c\uddff", "iso": "NZ"},
  {"code": "+505", "country": "Nicaragua", "flag": "\ud83c\uddf3\ud83c\uddee", "iso": "NI"},
  {"code": "+227", "country": "Niger", "flag": "\ud83c\uddf3\ud83c\uddea", "iso": "NE"},
  {"code": "+234", "country": "Nigeria", "flag": "\ud83c\uddf3\ud83c\uddec", "iso": "NG"},
  {"code": "+683", "country": "Niue", "flag": "\ud83c\uddf3\ud83c\uddfa", "iso": "NU"},
  {"code": "+672", "country": "Norfolk Island", "flag": "\ud83c\uddf3\ud83c\uddeb", "iso": "NF"},
  {"code": "+850", "country": "North Korea", "flag": "\ud83c\uddf0\ud83c\uddf5", "iso": "KP"},
  {"code": "+389", "country": "North Macedonia", "flag": "\ud83c\uddf2\ud83c\uddf0", "iso": "MK"},
  {"code": "+1670", "country": "Northern Mariana Islands", "flag": "\ud83c\uddf2\ud83c\uddf5", "iso": "MP"},
  {"code": "+47", "country": "Norway", "flag": "\ud83c\uddf3\ud83c\uddf4", "iso": "NO"},
  {"code": "+968", "country": "Oman", "flag": "\ud83c\uddf4\ud83c\uddf2", "iso": "OM"},
  {"code": "+92", "country": "Pakistan", "flag": "\ud83c\uddf5\ud83c\uddf0", "iso": "PK"},
  {"code": "+680", "country": "Palau", "flag": "\ud83c\uddf5\ud83c\uddfc", "iso": "PW"},
  {"code": "+970", "country": "Palestine", "flag": "\ud83c\uddf5\ud83c\uddf8", "iso": "PS"},
  {"code": "+507", "country": "Panama", "flag": "\ud83c\uddf5\ud83c\udde6", "iso": "PA"},
  {"code": "+675", "country": "Papua New Guinea", "flag": "\ud83c\uddf5\ud83c\uddec", "iso": "PG"},
  {"code": "+595", "country": "Paraguay", "flag": "\ud83c\uddf5\ud83c\uddfe", "iso": "PY"},
  {"code": "+51", "country": "Peru", "flag": "\ud83c\uddf5\ud83c\uddea", "iso": "PE"},
  {"code": "+63", "country": "Philippines", "flag": "\ud83c\uddf5\ud83c\udded", "iso": "PH"},
  {"code": "+64", "country": "Pitcairn Islands", "flag": "\ud83c\uddf5\ud83c\uddf3", "iso": "PN"},
  {"code": "+48", "country": "Poland", "flag": "\ud83c\uddf5\ud83c\uddf1", "iso": "PL"},
  {"code": "+351", "country": "Portugal", "flag": "\ud83c\uddf5\ud83c\uddf9", "iso": "PT"},
  {"code": "+1787", "country": "Puerto Rico", "flag": "\ud83c\uddf5\ud83c\uddf7", "iso": "PR"},
  {"code": "+974", "country": "Qatar", "flag": "\ud83c\uddf6\ud83c\udde6", "iso": "QA"},
  {"code": "+40", "country": "Romania", "flag": "\ud83c\uddf7\ud83c\uddf4", "iso": "RO"},
  {"code": "+73", "country": "Russia", "flag": "\ud83c\uddf7\ud83c\uddfa", "iso": "RU"},
  {"code": "+250", "country": "Rwanda", "flag": "\ud83c\uddf7\ud83c\uddfc", "iso": "RW"},
  {"code": "+262", "country": "R\u00e9union", "flag": "\ud83c\uddf7\ud83c\uddea", "iso": "RE"},
  {"code": "+590", "country": "Saint Barth\u00e9lemy", "flag": "\ud83c\udde7\ud83c\uddf1", "iso": "BL"},
  {"code": "+290", "country": "Saint Helena, Ascension and Tristan da Cunha", "flag": "\ud83c\uddf8\ud83c\udded", "iso": "SH"},
  {"code": "+1869", "country": "Saint Kitts and Nevis", "flag": "\ud83c\uddf0\ud83c\uddf3", "iso": "KN"},
  {"code": "+1758", "country": "Saint Lucia", "flag": "\ud83c\uddf1\ud83c\udde8", "iso": "LC"},
  {"code": "+590", "country": "Saint Martin", "flag": "\ud83c\uddf2\ud83c\uddeb", "iso": "MF"},
  {"code": "+508", "country": "Saint Pierre and Miquelon", "flag": "\ud83c\uddf5\ud83c\uddf2", "iso": "PM"},
  {"code": "+1784", "country": "Saint Vincent and the Grenadines", "flag": "\ud83c\uddfb\ud83c\udde8", "iso": "VC"},
  {"code": "+685", "country": "Samoa", "flag": "\ud83c\uddfc\ud83c\uddf8", "iso": "WS"},
  {"code": "+378", "country": "San Marino", "flag": "\ud83c\uddf8\ud83c\uddf2", "iso": "SM"},
  {"code": "+966", "country": "Saudi Arabia", "flag": "\ud83c\uddf8\ud83c\udde6", "iso": "SA"},
  {"code": "+221", "country": "Senegal", "flag": "\ud83c\uddf8\ud83c\uddf3", "iso": "SN"},
  {"code": "+381", "country": "Serbia", "flag": "\ud83c\uddf7\ud83c\uddf8", "iso": "RS"},
  {"code": "+248", "country": "Seychelles", "flag": "\ud83c\uddf8\ud83c\udde8", "iso": "SC"},
  {"code": "+232", "country": "Sierra Leone", "flag": "\ud83c\uddf8\ud83c\uddf1", "iso": "SL"},
  {"code": "+65", "country": "Singapore", "flag": "\ud83c\uddf8\ud83c\uddec", "iso": "SG"},
  {"code": "+1721", "country": "Sint Maarten", "flag": "\ud83c\uddf8\ud83c\uddfd", "iso": "SX"},
  {"code": "+421", "country": "Slovakia", "flag": "\ud83c\uddf8\ud83c\uddf0", "iso": "SK"},
  {"code": "+386", "country": "Slovenia", "flag": "\ud83c\uddf8\ud83c\uddee", "iso": "SI"},
  {"code": "+677", "country": "Solomon Islands", "flag": "\ud83c\uddf8\ud83c\udde7", "iso": "SB"},
  {"code": "+252", "country": "Somalia", "flag": "\ud83c\uddf8\ud83c\uddf4", "iso": "SO"},
  {"code": "+27", "country": "South Africa", "flag": "\ud83c\uddff\ud83c\udde6", "iso": "ZA"},
  {"code": "+500", "country": "South Georgia", "flag": "\ud83c\uddec\ud83c\uddf8", "iso": "GS"},
  {"code": "+82", "country": "South Korea", "flag": "\ud83c\uddf0\ud83c\uddf7", "iso": "KR"},
  {"code": "+211", "country": "South Sudan", "flag": "\ud83c\uddf8\ud83c\uddf8", "iso": "SS"},
  {"code": "+34", "country": "Spain", "flag": "\ud83c\uddea\ud83c\uddf8", "iso": "ES"},
  {"code": "+94", "country": "Sri Lanka", "flag": "\ud83c\uddf1\ud83c\uddf0", "iso": "LK"},
  {"code": "+249", "country": "Sudan", "flag": "\ud83c\uddf8\ud83c\udde9", "iso": "SD"},
  {"code": "+597", "country": "Suriname", "flag": "\ud83c\uddf8\ud83c\uddf7", "iso": "SR"},
  {"code": "+4779", "country": "Svalbard and Jan Mayen", "flag": "\ud83c\uddf8\ud83c\uddef", "iso": "SJ"},
  {"code": "+46", "country": "Sweden", "flag": "\ud83c\uddf8\ud83c\uddea", "iso": "SE"},
  {"code": "+41", "country": "Switzerland", "flag": "\ud83c\udde8\ud83c\udded", "iso": "CH"},
  {"code": "+963", "country": "Syria", "flag": "\ud83c\uddf8\ud83c\uddfe", "iso": "SY"},
  {"code": "+239", "country": "S\u00e3o Tom\u00e9 and Pr\u00edncipe", "flag": "\ud83c\uddf8\ud83c\uddf9", "iso": "ST"},
  {"code": "+886", "country": "Taiwan", "flag": "\ud83c\uddf9\ud83c\uddfc", "iso": "TW"},
  {"code": "+992", "country": "Tajikistan", "flag": "\ud83c\uddf9\ud83c\uddef", "iso": "TJ"},
  {"code": "+255", "country": "Tanzania", "flag": "\ud83c\uddf9\ud83c\uddff", "iso": "TZ"},
  {"code": "+66", "country": "Thailand", "flag": "\ud83c\uddf9\ud83c\udded", "iso": "TH"},
  {"code": "+670", "country": "Timor-Leste", "flag": "\ud83c\uddf9\ud83c\uddf1", "iso": "TL"},
  {"code": "+228", "country": "Togo", "flag": "\ud83c\uddf9\ud83c\uddec", "iso": "TG"},
  {"code": "+690", "country": "Tokelau", "flag": "\ud83c\uddf9\ud83c\uddf0", "iso": "TK"},
  {"code": "+676", "country": "Tonga", "flag": "\ud83c\uddf9\ud83c\uddf4", "iso": "TO"},
  {"code": "+1868", "country": "Trinidad and Tobago", "flag": "\ud83c\uddf9\ud83c\uddf9", "iso": "TT"},
  {"code": "+216", "country": "Tunisia", "flag": "\ud83c\uddf9\ud83c\uddf3", "iso": "TN"},
  {"code": "+993", "country": "Turkmenistan", "flag": "\ud83c\uddf9\ud83c\uddf2", "iso": "TM"},
  {"code": "+1649", "country": "Turks and Caicos Islands", "flag": "\ud83c\uddf9\ud83c\udde8", "iso": "TC"},
  {"code": "+688", "country": "Tuvalu", "flag": "\ud83c\uddf9\ud83c\uddfb", "iso": "TV"},
  {"code": "+90", "country": "T\u00fcrkiye", "flag": "\ud83c\uddf9\ud83c\uddf7", "iso": "TR"},
  {"code": "+256", "country": "Uganda", "flag": "\ud83c\uddfa\ud83c\uddec", "iso": "UG"},
  {"code": "+380", "country": "Ukraine", "flag": "\ud83c\uddfa\ud83c\udde6", "iso": "UA"},
  {"code": "+971", "country": "United Arab Emirates", "flag": "\ud83c\udde6\ud83c\uddea", "iso": "AE"},
  {"code": "+44", "country": "United Kingdom", "flag": "\ud83c\uddec\ud83c\udde7", "iso": "GB"},
  {"code": "+1201", "country": "United States", "flag": "\ud83c\uddfa\ud83c\uddf8", "iso": "US"},
  {"code": "+268", "country": "United States Minor Outlying Islands", "flag": "\ud83c\uddfa\ud83c\uddf2", "iso": "UM"},
  {"code": "+1340", "country": "United States Virgin Islands", "flag": "\ud83c\uddfb\ud83c\uddee", "iso": "VI"},
  {"code": "+598", "country": "Uruguay", "flag": "\ud83c\uddfa\ud83c\uddfe", "iso": "UY"},
  {"code": "+998", "country": "Uzbekistan", "flag": "\ud83c\uddfa\ud83c\uddff", "iso": "UZ"},
  {"code": "+678", "country": "Vanuatu", "flag": "\ud83c\uddfb\ud83c\uddfa", "iso": "VU"},
  {"code": "+3906698", "country": "Vatican City", "flag": "\ud83c\uddfb\ud83c\udde6", "iso": "VA"},
  {"code": "+58", "country": "Venezuela", "flag": "\ud83c\uddfb\ud83c\uddea", "iso": "VE"},
  {"code": "+84", "country": "Vietnam", "flag": "\ud83c\uddfb\ud83c\uddf3", "iso": "VN"},
  {"code": "+681", "country": "Wallis and Futuna", "flag": "\ud83c\uddfc\ud83c\uddeb", "iso": "WF"},
  {"code": "+2125288", "country": "Western Sahara", "flag": "\ud83c\uddea\ud83c\udded", "iso": "EH"},
  {"code": "+967", "country": "Yemen", "flag": "\ud83c\uddfe\ud83c\uddea", "iso": "YE"},
  {"code": "+260", "country": "Zambia", "flag": "\ud83c\uddff\ud83c\uddf2", "iso": "ZM"},
  {"code": "+263", "country": "Zimbabwe", "flag": "\ud83c\uddff\ud83c\uddfc", "iso": "ZW"},
  {"code": "+35818", "country": "\u00c5land Islands", "flag": "\ud83c\udde6\ud83c\uddfd", "iso": "AX"},
];
